sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t pkhot/docker-react-new -f Dockerfile.dev .

script:
  - docker run -e CI=true pkhot/docker-react-new npm run test
